"""View capabilities.

- Definitions for common capabilities of pythonic containers
- Definitions for common collections of pythonic containers
"""

from __future__ import annotations

from .traits import (
    Addable,
    Appendable,
    Assignable,
    ChildObservable,
    Clearable,
    Containable,
    Convertible,
    Deletable,
    DescendantsObservable,
    Discardable,
    Initializable,
    Insertable,
    Nestable,
    Observable,
    Poppable,
    Removable,
    Sizeable,
    Subscriptable,
    is_addable,
    is_appendable,
    is_assignable,
    is_child_observable,
    is_clearable,
    is_containable,
    is_convertible,
    is_deletable,
    is_descendants_observable,
    is_discardable,
    is_initializable,
    is_insertable,
    is_nestable,
    is_observable,
    is_poppable,
    is_removable,
    is_sizeable,
    is_subscriptable,
)


__all__ = [
    "Addable",
    "Appendable",
    "Assignable",
    "ChildObservable",
    "Clearable",
    "Containable",
    "Convertible",
    "Deletable",
    "DescendantsObservable",
    "Discardable",
    "Initializable",
    "Insertable",
    "Nestable",
    "Observable",
    "Poppable",
    "Removable",
    "Sizeable",
    "Subscriptable",
    "is_addable",
    "is_appendable",
    "is_assignable",
    "is_child_observable",
    "is_clearable",
    "is_containable",
    "is_convertible",
    "is_deletable",
    "is_descendants_observable",
    "is_discardable",
    "is_initializable",
    "is_insertable",
    "is_nestable",
    "is_observable",
    "is_poppable",
    "is_removable",
    "is_sizeable",
    "is_subscriptable",
]
